### ISSUE TITLE
Review last pull-request

### ISSUE THREAD

**Issue by drlc** [LinksTeamAgile/HotelReservation#25]
@LinksTeamAgile/agileteam read the comments about the code here:
https://github.com/LinksTeamAgile/HotelReservation/pull/16
then leave a comment down below with an ok.

**Comment by drlc** [comment]
ok

**Comment by apocaliss92** [comment]
ok

**Comment by Gianlucadv** [comment]
ok

**Comment by annalisaT91** [comment]
ok

**Comment by mirutech** [comment]
Ok

**Comment by KristalSiderglace** [comment]
Ok
