### ISSUE TITLE
delete Items

### ISSUE THREAD

**Issue by drlc** [LinksTeamAgile/HotelReservation#26]
Make a refactoring of delete methods on Sys.

**Branch assigned**: refactorDelete
**Priority**: 2/5
**Deadline**: 1/11

**Comment by johnnyupset** [comment]
The delete methods in Sys.java will stay the same, impossible to refactor for now.

**Comment by johnnyupset** [comment]
Now the delete methods use the Iterator<Room/Customer/Reservation> to scroll the lists

**Comment by drlc** [comment]
resolved in #66
