### ISSUE TITLE
stream for reservation-entry

### ISSUE THREAD

**Issue by drlc** [LinksTeamAgile/HotelReservation#35]
Create the stream for data entry on Controller. Make the methods for reservation entry.

**Branch assigned**: controllerReservation
**Priority**: 5/5
**Deadline**: 2/11

**Comment by drlc** [comment]
resolved in #48

**Comment by Gianlucadv** [comment]
Ok, to get ID of customer but the user must just insert the number of guests and then the system must search automatically possible rooms.

**Comment by drlc** [comment]
I was thinking about it, and It's a really good feature: show possible rooms before type the id's of rooms. It will be implemented!
