### ISSUE TITLE
make filters

### ISSUE THREAD

**Issue by drlc** [LinksTeamAgile/HotelReservation#38]
Make Rooms and Customers filterable.

**Branch assigned**: filters
**Priority**: 4/5
**Deadline**: 2/11

**Comment by mirutech** [comment]
Partially solved

**Comment by drlc** [comment]
Solution refused. Still waiting for a new implementation.

**Comment by mirutech** [comment]
The implementation is good, the form must be changed. I suggest to devolve the code form changes to those who fully understands the realization of this code pattern.

**Comment by drlc** [comment]
This implementation is against SRP: in this way Sys is facing the implementation of showing items that have a particular property but the responsability to output the possible actions too.
That last thing must be done by the gui!
If you mind, you can refactor your code and do a pull-request again.

**Comment by mirutech** [comment]
Ok, I'll refactor the code ASAP.

**Comment by drlc** [comment]
Resolved in pull-request #44
