### ISSUE TITLE
Getting started is not straightforward

### ISSUE THREAD

**Issue by wbigger** [LinksTeamAgile/HotelReservation#72]
I would like to try the project, but it is not clear to me how to run it quickly. Which IDE should I use? Or should I run it using directly JDK?

Please add a getting started section in the readme!

**Comment by wbigger** [comment]
You can add these Eclipse instructions:
1) Import->Git->Projects from Git
2) Clone URI
3) Follow instructions
4) When asked, use import Wizard->Java project
5) in the new java project menu, uncheck "use default location", select the git repo location, click finish.

**Comment by wbigger** [comment]
Write down in the guide that user has also to add Junit to the eclipse project:

```
You add it to a project by right clicking the project in the Package Explorer and selecting
Build Path -> Add Libraries... Then simply select JUnit and click Next >
```

Specify also the requested JUnit version (I suppose JUnit4)

**Comment by wbigger** [comment]
The error message when project does not have the config file is great!
However, consider to add a sample configs.properties file to speed up the setup.

**Comment by wbigger** [comment]
Specify the sql-jdbc driver version (sqlite-jdbc-3.8.11.2) and possibly where to find it (for example [here](https://bitbucket.org/xerial/sqlite-jdbc/downloads)).

Instruction about how to add it to the project are also welcomed.

**Comment by mirutech** [comment]
README fixed
