### ISSUE TITLE
DB initialization is not static

### ISSUE THREAD

**Issue by wbigger** [LinksTeamAgile/HotelReservation#92]
Ottimizzazione suggerita da Andrea Camurri.

Per fare pratica con gli inizializzatori statici, nella classe di connessione al DB si può mettere qualcosa del tipo:

```
static {
    try {
        Class.forName("com.example.jdbc.Driver");
    } catch (ClassNotFoundException e) {
        throw new ExceptionInInitializerError("Cannot load JDBC driver.", e);
    }
}
```
Nel codice c'è un check, ma non come inizializzatore statico.

**Comment by mirutech** [comment]
Static DB initialization added.
